/* app.js - Main UI, navigation, alerts, portfolio - Stock Monitor Pro v7 */
function renderDash(){const td=TODAY[cur]||{};const p=liveP[cur]||td.price||0;const chg=td.change||0;const pct=td.pct||0;const arr=history[cur]?.[tf]||[];const high=arr.length?Math.round(Math.max(...arr)*100)/100:p;const low=arr.length?Math.round(Math.min(...arr)*100)/100:p;const sent=SENT(cur);document.getElementById('dm').innerHTML='<div class="mc"><div class="mcl">'+cur+' price</div><div class="mcv">$'+p.toFixed(2)+'</div><div class="mcs '+(chg>=0?'up':'dn')+'">'+(chg>=0?'+':'')+chg.toFixed(2)+' ('+(pct>=0?'+':'')+pct.toFixed(2)+'%)</div></div><div class="mc"><div class="mcl">Day high</div><div class="mcv up">$'+high.toFixed(2)+'</div></div><div class="mc"><div class="mcl">Day low</div><div class="mcv dn">$'+low.toFixed(2)+'</div></div><div class="mc"><div class="mcl">Sentiment</div><div class="mcv '+(sent>0.1?'up':sent<-0.1?'dn':'nu')+'">'+(sent>0?'+':'')+sent+'</div></div><div class="mc"><div class="mcl">Analyst target</div><div class="mcv up">$'+(td.target||'--')+'</div><div class="mcs up">'+(td.rating||'')+'</div></div>';}
function renderSignal(){const a=SIG(cur);const arr=history[cur]?.[tf]||[];const v=VERDICT(cur,a);const vel=document.getElementById('verdict');vel.className='verdict '+v.cls;vel.innerHTML='<div class="vtitle">'+v.icon+' - '+v.title+'</div><div class="vbody">'+v.body+'</div>';document.getElementById('cbadge').textContent=v.icon;document.getElementById('cbadge').className='badge '+(a.score>=2?'b-up':a.score<=0?'b-dn':'b-w');document.getElementById('srow').innerHTML=a.pills.map(p=>'<span class="spill '+p.c+'">'+p.t+'</span>').join('');const rsiCol=a.rsi>70?'#d84a30':a.rsi<30?'#1a9e75':'#378add';const vol=VOL(arr);const dir=a.ma5>a.ma20?1:-1;const fc20=Math.round((a.cur*(1+(dir*(vol/Math.max(a.cur,1))*20*0.28)))*100)/100;const risk=Math.min(10,Math.max(1,Math.round(5-a.score*1.3)));document.getElementById('igrid').innerHTML='<div class="ic"><div class="icl">Momentum</div><div class="icv" style="color:'+rsiCol+'">'+a.rsi+'/100</div><div class="icbar"><div class="icfill" style="width:'+a.rsi+'%;background:'+rsiCol+'"></div></div><div class="ics">'+(a.rsi>70?'Overbought - may drop':a.rsi<30?'Oversold - may bounce':'Normal (30-70)')+'</div></div><div class="ic"><div class="icl">vs 20-day avg</div><div class="icv">$'+(a.ma20||0).toFixed(2)+'</div><div class="icbar"><div class="icfill" style="width:50%;background:'+(a.cur>a.ma20?'#1a9e75':'#d84a30')+'"></div></div><div class="ics">Price is '+(a.cur>(a.ma20||0)?'ABOVE - healthy':'BELOW - weak')+'</div></div><div class="ic"><div class="icl">20-day forecast</div><div class="icv '+(fc20>=a.cur?'up':'dn')+'">$'+fc20.toFixed(2)+'</div><div class="ics">'+(fc20>=a.cur?'Trending up':'Trending down')+' '+(fc20>=a.cur?'+':'')+Math.round((fc20-a.cur)/Math.max(a.cur,1)*10000)/100+'% est.</div></div><div class="ic"><div class="icl">Risk level</div><div class="icv '+(risk>=7?'dn':risk<=3?'up':'nu')+'">'+risk+'/10</div><div class="icbar"><div class="icfill" style="width:'+risk*10+'%;background:'+(risk>=7?'#d84a30':risk<=3?'#1a9e75':'#ef9f27')+'"></div></div><div class="ics">'+(risk<=3?'Low risk':risk<=6?'Medium risk':'High risk - wait')+'</div></div>';}
function renderChart(){const arr=history[cur]?.[tf]||[];if(!arr.length)return;const color=STOCKS[cur]?.color||'#378add';const labels=getLabels(tf).slice(0,arr.length);const ma20=arr.map((_,i)=>i<20?null:MA(arr.slice(0,i+1),20));const ma5=arr.map((_,i)=>i<5?null:MA(arr.slice(0,i+1),5));const a=SIG(cur);const vol=VOL(arr);const dir=a.ma5>a.ma20?1:-1;const fcBase=arr[arr.length-1];const fcArr=Array.from({length:20},(_,i)=>Math.round((fcBase*(1+(dir*(vol/Math.max(fcBase,1))*(i+1)*0.28)))*100)/100);const extL=[...labels,...Array.from({length:20},(_,i)=>'F'+(i+1))];const extP=[...arr,...Array(20).fill(null)];const extM20=[...ma20,...Array(20).fill(null)];const extM5=[...ma5,...Array(20).fill(null)];const extFc=[...Array(arr.length-1).fill(null),fcBase,...fcArr];document.getElementById('cl').textContent=cur+' - '+(STOCKS[cur]?.name||cur);if(priceChart)priceChart.destroy();priceChart=new Chart(document.getElementById('pc'),{type:'line',data:{labels:extL,datasets:[{label:'Price',data:extP,borderColor:color,backgroundColor:color+'14',fill:true,tension:0.3,pointRadius:0,borderWidth:2},{label:'20-day avg',data:extM20,borderColor:'#ef9f27',fill:false,tension:0.3,pointRadius:0,borderWidth:1.5,borderDash:[4,3]},{label:'5-day avg',data:extM5,borderColor:'#1d9e75',fill:false,tension:0.3,pointRadius:0,borderWidth:1.5,borderDash:[2,2]},{label:'20-day forecast',data:extFc,borderColor:'#d84a30',fill:false,tension:0.3,pointRadius:0,borderWidth:1.5,borderDash:[6,3]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#888',font:{size:10},maxTicksLimit:9},grid:{color:'rgba(128,128,128,0.07)'}},y:{ticks:{color:'#888',font:{size:10},callback:v=>'$'+v.toFixed(0)},grid:{color:'rgba(128,128,128,0.07)'}}}}}); }
function showSec(id,btn){document.querySelectorAll('.sec').forEach(s=>s.classList.remove('on'));document.getElementById('sec-'+id).classList.add('on');document.querySelectorAll('.ntab').forEach(t=>t.classList.remove('on'));btn.classList.add('on');if(id==='port')renderPortfolio();if(id==='news'){renderNews();document.getElementById('newsDate').textContent=new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});}if(id==='alerts'){renderAlerts();renderLog();}}
function switchStock(s){cur=s;refreshDash();buildStabs();}
function setTF(t,btn){tf=t;document.querySelectorAll('.tf').forEach(b=>b.classList.remove('on'));btn.classList.add('on');refreshDash();}
function refreshDash(){renderDash();renderSignal();renderChart();}
function buildStabs(){document.getElementById('stabs').innerHTML=Object.keys(STOCKS).map(s=>{const td=TODAY[s]||{};const p=liveP[s]||td.price||0;const pct=td.pct||0;return'<button class="stab '+(s===cur?'on':'')+'" onclick="switchStock(''+s+'')"><div>'+s+'</div><div style="font-size:10px">$'+p.toFixed(0)+' <span style="color:'+(pct>=0?'#1a9e75':'#d84a30')+'">'+(pct>=0?'+':'')+pct.toFixed(1)+'%</span></div><div style="font-size:9px;color:var(--color-text-secondary)"><a href="pages/'+s.toLowerCase()+'.html" style="color:#1a73e8;text-decoration:none" onclick="event.stopPropagation()">detail</a></div></button>';}).join('');}
function populateSels(){const syms=Object.keys(STOCKS);['as','ps'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const v=el.value;el.innerHTML=syms.map(s=>'<option value="'+s+'">'+s+' - '+STOCKS[s].name+'</option>').join('');if(syms.includes(v))el.value=v;});const nf=document.getElementById('nf');if(nf)nf.innerHTML='<option value="ALL">All stocks</option>'+syms.map(s=>'<option value="'+s+'">'+s+'</option>').join('');}
function openDetail(){window.open('pages/'+cur.toLowerCase()+'.html','_blank');}
function testTick(){const arr=history[cur]?.[tf];if(!arr)return;const last=arr[arr.length-1];const next=Math.round((last+((Math.random()-.47)*last*.009))*100)/100;arr.push(next);if(arr.length>65)arr.shift();liveP[cur]=next;refreshDash();buildStabs();checkAlerts();addLog('[Test tick] '+cur+' to $'+next.toFixed(2),'i',false);}
function addAlert(){const stock=document.getElementById('as').value;const type=document.getElementById('at').value;const val=parseFloat(document.getElementById('av').value);const name=document.getElementById('an').value.trim();const email=document.getElementById('ae').value.trim();if(['below','above','pctdrop','critical'].includes(type)&&(isNaN(val)||!val)){alert('Enter a value.');return;}alerts.push({stock,type,val:val||0,name,email,id:Date.now()});localStorage.setItem('smv7_al',JSON.stringify(alerts));document.getElementById('av').value='';renderAlerts();addLog('Alert set: '+stock+' '+type+(val?' @ $'+val:''),'i',false);}
function delAlert(i){alerts.splice(i,1);localStorage.setItem('smv7_al',JSON.stringify(alerts));renderAlerts();}
function renderAlerts(){const el=document.getElementById('alist');if(!el)return;if(!alerts.length){el.innerHTML='<div class="li li-i">No alerts yet.</div>';return;}el.innerHTML=alerts.map((a,i)=>'<div class="ai"><span class="badge '+(a.type==='above'?'b-up':a.type==='critical'?'b-w':'b-dn')+'">'+a.type+'</span><strong>'+a.stock+'</strong><span>'+(a.val?'$'+a.val:'')+'</span><span style="font-size:10px;color:var(--color-text-secondary)">'+(a.name||'')+' '+(a.email?'- '+a.email:'')+'</span><button class="xbtn" onclick="delAlert('+i+')">x</button></div>').join('');}
async function checkAlerts(){for(const a of alerts){const arr=history[a.stock]?.[tf];if(!arr||arr.length<2)continue;const c=arr[arr.length-1];const pv=arr[arr.length-2];const chgPct=Math.round((c-pv)/pv*10000)/100;const sig=SIG(a.stock);const ck=a.stock+'_'+a.type+'_'+a.val;if(cooldowns[ck]&&Date.now()-cooldowns[ck]<3600000)continue;let trig=false,reason='',aType='';if(a.type==='below'&&c<=a.val){trig=true;aType='Price Drop';reason=a.stock+' dropped to $'+c.toFixed(2)+', below $'+a.val;}else if(a.type==='above'&&c>=a.val){trig=true;aType='Target Reached';reason=a.stock+' reached $'+c.toFixed(2);}else if(a.type==='pctdrop'&&chgPct<=-a.val){trig=true;aType='% Drop Alert';reason=a.stock+' dropped '+chgPct+'%';}else if(a.type==='critical'&&c<a.val){trig=true;aType='CRITICAL';reason='CRITICAL: '+a.stock+' at $'+c.toFixed(2);}else if(a.type==='rsi_low'&&sig.rsi<30){trig=true;aType='Oversold';reason=a.stock+' RSI='+sig.rsi;}else if(a.type==='rsi_high'&&sig.rsi>70){trig=true;aType='Overbought';reason=a.stock+' RSI='+sig.rsi;}if(trig){cooldowns[ck]=Date.now();const chg=Math.round((c-pv)*100)/100;const risk=Math.min(10,Math.max(1,Math.round(5-sig.score*1.3)));const vd=VERDICT(a.stock,sig);const vol=VOL(arr);const dir=sig.ma5>sig.ma20?1:-1;const fc=Math.round((c*(1+(dir*(vol/Math.max(c,1))*20*.28)))*100)/100;let lmAnalysis='N/A';try{lmAnalysis=await callLMStudio([{role:'system',content:buildSystemPrompt()},{role:'user',content:'Alert: '+reason+'. 1-sentence recommendation.'}],80);}catch(e){}const sent=await sendEmail({stock:a.stock,name:a.name||settings.name,email:a.email||settings.email,alertType:aType,cur:c,change:String(chg),changePct:String(chgPct),rsi:sig.rsi,ma20:sig.ma20,sent:sig.sent,signal:vd.icon,reason,fc:fc.toFixed(2),fcDir:fc>=c?'Upward':'Downward',risk,lmAnalysis,newsSummary:buildNewsSummary(a.stock)});const lt=aType.includes('CRITICAL')||aType.toLowerCase().includes('drop')?'dn':aType.includes('Reached')||aType.includes('Oversold')?'up':'w';addLog(reason,lt,sent);}}}
function addLog(msg,type,sent){logs.unshift({msg,type,sent,time:new Date().toLocaleTimeString()});if(logs.length>50)logs=logs.slice(0,50);localStorage.setItem('smv7_log',JSON.stringify(logs));if(document.getElementById('loglist'))renderLog();}
function renderLog(){const el=document.getElementById('loglist');if(!el)return;if(!logs.length){el.innerHTML='<div class="li li-i">No alerts fired yet.</div>';return;}el.innerHTML=logs.slice(0,30).map(l=>'<div class="li li-'+l.type+'"><strong>'+l.time+'</strong> - '+l.msg+(l.sent?' <em>[email sent]</em>':l.sent===false?' <em>[logged]</em>':'')+'</div>').join('');}
function clearLog(){logs=[];localStorage.setItem('smv7_log','[]');renderLog();}
function addPos(){const stock=document.getElementById('ps').value;const shares=parseFloat(document.getElementById('psh').value);const bp=parseFloat(document.getElementById('pbp').value);if(!shares||!bp){alert('Enter shares and buy price.');return;}positions.push({stock,shares,buyPrice:bp});localStorage.setItem('smv7_pos',JSON.stringify(positions));document.getElementById('psh').value='';document.getElementById('pbp').value='';document.getElementById('apf').style.display='none';renderPortfolio();}
function delPos(i){positions.splice(i,1);localStorage.setItem('smv7_pos',JSON.stringify(positions));renderPortfolio();}
function renderPortfolio(){if(!positions.length){document.getElementById('plist').innerHTML='<div class="li li-i">No positions yet.</div>';document.getElementById('pm').innerHTML='';return;}let ti=0,tc=0;const rows=positions.map(p=>{const c=liveP[p.stock]||p.buyPrice;const inv=Math.round(p.shares*p.buyPrice*100)/100;const now=Math.round(p.shares*c*100)/100;const pnl=Math.round((now-inv)*100)/100;const pct=Math.round(pnl/inv*10000)/100;ti+=inv;tc+=now;return{...p,c,inv,now,pnl,pct};});ti=Math.round(ti*100)/100;tc=Math.round(tc*100)/100;const tpnl=Math.round((tc-ti)*100)/100;const tpct=Math.round(tpnl/ti*10000)/100;document.getElementById('pm').innerHTML='<div class="mc"><div class="mcl">Invested</div><div class="mcv">$'+ti.toLocaleString()+'</div></div><div class="mc"><div class="mcl">Current</div><div class="mcv">$'+tc.toLocaleString()+'</div></div><div class="mc"><div class="mcl">P&L</div><div class="mcv '+(tpnl>=0?'up':'dn')+'">'+(tpnl>=0?'+':'')+tpnl.toFixed(2)+'</div><div class="mcs '+(tpnl>=0?'up':'dn')+'">'+(tpct>=0?'+':'')+tpct+'%</div></div>';document.getElementById('plist').innerHTML=rows.map((p,i)=>'<div class="prow"><strong>'+p.stock+'</strong><span>'+p.shares+' @ $'+p.buyPrice+'</span><span>$'+p.c.toFixed(2)+'</span><span class="'+(p.pnl>=0?'up':'dn')+'">'+(p.pnl>=0?'+':'')+p.pnl.toFixed(2)+' ('+(p.pct>=0?'+':'')+p.pct+'%)</span><button class="xbtn" onclick="delPos('+i+')">x</button></div>').join('');if(pieChart)pieChart.destroy();pieChart=new Chart(document.getElementById('piec'),{type:'doughnut',data:{labels:rows.map(r=>r.stock),datasets:[{data:rows.map(r=>Math.round(r.now*100)/100),backgroundColor:['#378add','#1d9e75','#d84a30','#534ab7','#ef9f27','#185fa5'].slice(0,rows.length),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});}
function renderNews(){const f=document.getElementById('nf')?.value||'ALL';let items=[];if(f==='ALL'){items=[...NEWS.MARKET];for(const s in STOCKS)items.push(...(NEWS[s]||[]));}else items=[...NEWS.MARKET,...(NEWS[f]||[])];items.sort((a,b)=>b.s-a.s);document.getElementById('nlist').innerHTML=items.map(n=>'<div class="nitem '+(n.s>0.2?'n-bull':n.s<-0.1?'n-bear':'n-neu')+'"><div class="nh">'+n.h+'</div><div class="nm"><span class="badge '+(n.s>0.1?'b-up':n.s<-0.1?'b-dn':'b-nu')+'">'+n.l+'</span><span style="font-size:10px;color:var(--color-text-secondary)">'+n.stock+' - '+n.src+' - '+n.date+' - score: '+(n.s>0?'+':'')+n.s+'</span></div></div>').join('');document.getElementById('sentm').innerHTML=Object.keys(STOCKS).map(s=>{const v=SENT(s);return'<div class="mc"><div class="mcl">'+s+'</div><div class="mcv '+(v>0.1?'up':v<-0.1?'dn':'nu')+'">'+(v>0?'+':'')+v+'</div><div class="mcs '+(v>0.1?'up':v<-0.1?'dn':'nu')+'">'+(v>0.2?'Positive':v<-0.1?'Negative':'Mixed')+'</div></div>';}).join('');}
async function addCustom(){const t=document.getElementById('ct').value.toUpperCase().trim();const n=document.getElementById('cn').value.trim();if(!t||!n){alert('Enter ticker and name.');return;}document.getElementById('cmsg').textContent='Fetching price for '+t+'...';let base=100;try{const r=await fetch('https://query1.finance.yahoo.com/v8/finance/chart/'+t+'?interval=1d&range=1d');if(r.ok){const d=await r.json();const p=d?.chart?.result?.[0]?.meta?.regularMarketPrice;if(p&&p>0)base=Math.round(p*100)/100;}}catch(e){}STOCKS[t]={name:n,color:'#534ab7'};TODAY[t]={price:base,prev:base,change:0,pct:0,target:Math.round(base*1.15),rating:'N/A'};NEWS[t]=[];liveP[t]=base;const vol=base*.006;history[t]={'1D':genHist(base,28,vol*.4),'1W':genHist(base,35,vol*.85),'1M':genHist(base,30,vol*1.6)};populateSels();buildStabs();document.getElementById('cmsg').textContent=t+' added at $'+base.toFixed(2);}
function toggleEl(id){const e=document.getElementById(id);e.style.display=e.style.display==='none'?'block':'none';}
if(settings.name)document.getElementById('cfgn').value=settings.name;
if(settings.email)document.getElementById('cfge').value=settings.email;
const savedToken=localStorage.getItem('smv7_apify_token');
if(savedToken&&document.getElementById('apify-token'))document.getElementById('apify-token').value=savedToken;
populateSels();
initAll();
setInterval(()=>{fetchLive();checkAlerts();},300000);
addLog('v7 started - service_3rss6un - LM Studio Qwen2.5 7B - Apify - Jun 2026','i',false);
