/* lmstudio.js - LM Studio AI Chat - Stock Monitor Pro v7 */
/* Model: qwen2.5-7b-instruct | Server: 127.0.0.1:1234 | Token: sk-lm-s638fAhx:6OJ4Ll16GiRG6m3K9ptk */
async function callLMStudio(messages,maxTokens=512){const res=await fetch(LM_BASE+'/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+LM_TOKEN},body:JSON.stringify({model:LM_MODEL,messages,max_tokens:maxTokens,temperature:0.7,stream:false})});if(!res.ok)throw new Error('LM Studio '+res.status+': '+await res.text());const data=await res.json();return data.choices?.[0]?.message?.content||data.content?.[0]?.text||'[No response]';}
function buildSystemPrompt(){const ctx=Object.keys(STOCKS).map(s=>{const td=TODAY[s]||{};const p=liveP[s]||td.price||0;const sig=SIG(s);return s+' ('+STOCKS[s].name+'): price=$'+p.toFixed(2)+', change='+(td.pct>=0?'+':'')+td.pct?.toFixed(2)+'%, RSI='+sig.rsi+', MA20=$'+sig.ma20?.toFixed(2)+', score='+sig.score+'/4, verdict='+VERDICT(s,sig).icon+', sentiment='+SENT(s);}).join('\n');return 'You are a professional stock market analyst for Stock Monitor Pro.\nLive data as of '+new Date().toLocaleDateString()+':\n'+ctx+'\n\nGive clear Buy/Hold/Sell recommendations. Explain in simple English. Keep answers 3-5 sentences. Always note you are not a licensed financial advisor.';}
async function sendAI(){const input=document.getElementById('ai-input').value.trim();if(!input)return;document.getElementById('ai-input').value='';appendAIMessage(input,'user');const loadingId=appendAIMessage('Thinking...','loading');aiHistory.push({role:'user',content:input});try{const messages=[{role:'system',content:buildSystemPrompt()},...aiHistory.slice(-8)];const reply=await callLMStudio(messages);aiHistory.push({role:'assistant',content:reply});updateAIMessage(loadingId,reply,'bot');document.getElementById('ai-status').textContent='Connected';document.getElementById('ai-status').className='badge b-up';}catch(err){updateAIMessage(loadingId,'LM Studio error: '+err.message+'. Make sure LM Studio is running at 127.0.0.1:1234.','bot');document.getElementById('ai-status').textContent='Disconnected';document.getElementById('ai-status').className='badge b-dn';}}
function aiQuick(prompt){document.getElementById('ai-input').value=prompt;sendAI();}
function aiContext(){const ctx=Object.keys(STOCKS).map(s=>{const sig=SIG(s);const vd=VERDICT(s,sig);return s+': $'+(liveP[s]||TODAY[s]?.price||0).toFixed(2)+' - '+vd.icon+' - RSI '+sig.rsi;}).join(' | ');document.getElementById('ai-input').value='Here is today summary: '+ctx+'. Which stock looks best?';}
function clearAIChat(){aiHistory=[];document.getElementById('ai-chat-box').innerHTML='<div style="color:var(--color-text-secondary)">Chat cleared. Ask me anything about your stocks.</div>';}
async function testLMStudio(){showResult('lm-msg','Testing connection to http://127.0.0.1:1234...','#faeeda','#854f0b');try{const reply=await callLMStudio([{role:'system',content:'You are a helpful assistant.'},{role:'user',content:'Reply with exactly: "LM Studio connected successfully."'}],20);showResult('lm-msg','Connected! Model replied: '+reply,'#e1f5ee','#0f6e56');document.getElementById('ai-status').textContent='Connected';document.getElementById('ai-status').className='badge b-up';}catch(err){showResult('lm-msg','Connection failed: '+err.message,'#faece7','#993c1d');document.getElementById('ai-status').textContent='Disconnected';document.getElementById('ai-status').className='badge b-dn';}}
let _aiMsgId=0;
function appendAIMessage(text,type){const id='ai-msg-'+(_aiMsgId++);const box=document.getElementById('ai-chat-box');const div=document.createElement('div');div.className='ai-msg '+type;div.id=id;div.textContent=text;box.appendChild(div);box.scrollTop=box.scrollHeight;return id;}
function updateAIMessage(id,text,type){const el=document.getElementById(id);if(!el)return;el.className='ai-msg '+type;el.textContent=text;document.getElementById('ai-chat-box').scrollTop=9999;}
