/* signals.js - Technical Analysis - Stock Monitor Pro v7 */
function genHist(base,n,vol){const a=[];let p=base*(0.93+Math.random()*.07);for(let i=0;i<n;i++){p+=((Math.random()-.478)*vol);a.push(Math.round(p*100)/100);}a[a.length-1]=Math.round(base*100)/100;return a;}
function initAll(){for(const s in STOCKS){const base=TODAY[s]?.price||100;liveP[s]=base;const vol=base*.006;history[s]={'1D':genHist(base,28,vol*.4),'1W':genHist(base,35,vol*.85),'1M':genHist(base,30,vol*1.6);};}fetchLive();}
async function fetchLive(){let ok=0;for(const s of Object.keys(STOCKS)){try{const r=await fetch('https://query1.finance.yahoo.com/v8/finance/chart/'+s+'?interval=1d&range=1d');if(!r.ok)throw 0;const d=await r.json();const p=d?.chart?.result?.[0]?.meta?.regularMarketPrice;if(p&&p>0){liveP[s]=Math.round(p*100)/100;history[s]['1D'][history[s]['1D'].length-1]=liveP[s];ok++;}}catch(e){}}document.getElementById('lb').textContent=ok>0?'Live':'Cached';document.getElementById('lastupdated').textContent=(ok>0?'Live prices · ':' Cached · ')+'Apify news · service_3rss6un · LM Studio · '+new Date().toLocaleTimeString();refreshDash();buildStabs();populateSels();}
function MA(a,n){if(a.length<n)return a[a.length-1];return Math.round(a.slice(-n).reduce((x,y)=>x+y,0)/n*100)/100;}
function RSI(a){const n=Math.min(14,a.length-1);let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l+=Math.abs(d);}if(!l)return 100;return Math.round(100-(100/(1+g/l)));}
function VOL(a){const n=Math.min(14,a.length);const s=a.slice(-n);const m=s.reduce((x,y)=>x+y,0)/n;return Math.round(Math.sqrt(s.reduce((x,y)=>x+(y-m)**2,0)/n)*100)/100;}
function SENT(s){const items=[...(NEWS[s]||[]),...(NEWS.MARKET||[])];if(!items.length)return 0;return Math.round(items.reduce((a,b)=>a+b.s,0)/items.length*100)/100;}
function SIG(s){const arr=history[s]?.[tf];if(!arr||!arr.length)return{score:0,pills:[],rsi:50,ma5:0,ma20:0,cur:liveP[s]||0,sent:0};const c=arr[arr.length-1];const rsi=RSI(arr);const ma5=MA(arr,5);const ma20=MA(arr,20);const sent=SENT(s);let score=0,pills=[];if(rsi<40){score++;pills.push({t:'Momentum: low (may rise)',c:'s-up'});}else if(rsi>65){score--;pills.push({t:'Momentum: high (may drop)',c:'s-dn'});}else pills.push({t:'Momentum: normal',c:'s-nu'});if(c>ma20){score++;pills.push({t:'Above 20-day average',c:'s-up'});}else{score--;pills.push({t:'Below 20-day average',c:'s-dn'});}if(ma5>ma20){score++;pills.push({t:'Short-term uptrend',c:'s-up'});}else pills.push({t:'No clear uptrend',c:'s-nu'});if(sent>0.2){score++;pills.push({t:'News: positive',c:'s-up'});}else if(sent<-0.1){score--;pills.push({t:'News: negative',c:'s-dn'});}else pills.push({t:'News: mixed',c:'s-nu'});return{score,pills,rsi,ma5,ma20,cur:c,sent};}
function VERDICT(s,a){const td=TODAY[s]||{};const pct=td.pct||0;const rating=td.rating||'Hold';if(a.score>=3)return{cls:'v-buy',icon:'BUY',title:'Good time to consider investing',body:STOCKS[s].name+' is up '+(pct>=0?'+':'')+pct.toFixed(2)+'% today. Analyst: '+rating+' target $'+td.target+'.'};if(a.score>=1)return{cls:'v-hold',icon:'HOLD',title:'Hold - wait for clearer signal',body:STOCKS[s].name+' has mixed signals. Analyst target: $'+td.target+'.'};if(a.score===0)return{cls:'v-hold',icon:'WAIT',title:'Wait - signals are unclear',body:STOCKS[s].name+' technical signals not aligned.'};return{cls:'v-sell',icon:'CAUTION',title:'Caution - risky right now',body:STOCKS[s].name+' shows weak signals.'};}
function getLabels(t){if(t==='1D')return Array.from({length:28},(_,i)=>{const h=9+Math.floor(i/2);return h+':'+(i%2===0?'00':'30');});if(t==='1W')return Array.from({length:35},(_,i)=>['M','T','W','T','F'][i%5]+'W'+(Math.floor(i/5)+1));return Array.from({length:30},(_,i)=>'D'+(i+1));}
